export const cartoonsDetails = {
  regularShow: {
    titlePt: 'Apenas Um Show',
    titleEn: 'Regular Show',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  jorelsBrother: {
    titlePt: 'Irmão do Jorel',
    titleEn: "Jorel's Brother",
    duration: 10,
    year: 2014,
    origin: 'Brasil',
    contentClassification: 'Obra não publicitária brasileira, constituinte de espaço qualificado e independente',
    indicativeClassification: '10',
    synopsis: 'Irmão do Jorel é o filho caçula de uma excêntrica família de acumuladores presa nos anos 80 e com a ajuda de sua melhor amiga, ele enfrenta os primeiros obstáculos da vida num ritmo alucinante. Sem diferenciar fantasia e realidade, ele sempre descobre uma maneira absurda de sair da sombra de seu irmão celebridade, mas seu verdadeiro nome é sempre um mistério para todos.',
    genre: 'Animação, Comédia',
    director: 'Juliano Enrico',
    casting: ''
  },
  thePowerpuffGirls: {
    titlePt: 'As Meninas Superpoderosas',
    titleEn: 'The Powerpuff Girls',
    duration: 60,
    year: 2016,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 'Livre',
    synopsis: 'A cidade de Townsville pode ser uma metrópole bela e agitada, mas não se deixe enganar! O mal está à espreita e somente três menininhas superpoderosas são capazes de manter os vilões bem longe: Florzinha, Lindinha e Docinho! Conciliar a escola, a hora de dormir e derrotar monstros gigantes é mesmo complicado, mas, juntas, As Meninas Superpoderosas dão conta do recado! Enfrentando um bando de vilões, elas mostram o verdadeiro significado da frase "brigar como uma menininha". Novos inimigos e novas aventuras aguardam você na estreia da nova série de As Meninas Superpoderosas!',
    genre: 'Animação, Aventura, Comédia',
    director: 'Craig Mccraken',
    casting: ''
  },
  tomAndJerry: {
    titlePt: 'O Show de Tom e Jerry',
    titleEn: 'The Tom & Jerry Show',
    duration: 15,
    year: 2013,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 'Livre',
    synopsis: 'Junte-se a Tom e Jerry enquanto os dois disputam território. Eles vão aprontar novas e hilárias travessuras, torcendo para não ser pegos!',
    genre: 'Animação',
    director: '',
    casting: ''
  },
  dragonBall: {
    titlePt: 'Dragon Ball Super',
    titleEn: 'Dragon Ball Super',
    duration: 30,
    year: 2015,
    origin: 'Japão',
    contentClassification: '04',
    indicativeClassification: '10',
    synopsis: 'Após a derrota de Majin Buu, Goku assumiu o novo papel de¿ produtor de rabanetes?! A Terra está em paz e nossos heróis agora levam vidas normais. Mas eles não podem se acomodar. Num lugar distante, o poderoso Deus da Destruição, Beerus, desperta para uma profecia que revela seu fim pelas mãos de um ser ainda mais formidável. Quando a busca pelo Deus Saiyan os traz à Terra, poderão Goku e seus amigos enfrentar seu inimigo mais forte até hoje?',
    genre: 'Anime',
    director: '',
    casting: ''
  },
  scoobyDoo: {
    titlePt: 'Que Legal, Scooby-Doo!',
    titleEn: 'Be Cool Scooby Doo',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 'Livre',
    synopsis: 'A gangue põe o pé na estrada mais uma vez, a bordo da Máquina de Mistério, em busca de diversão e aventura. O problema é que os monstros e a confusão continuam no caminho! Desta vez, a galera vai tentar solucionar os novos e infindáveis enigmas que a espera. Por sorte, Salsicha e Scooby estão mais "corajosos e heroicos" do que nunca... à sua própria moda, é claro: com seu famoso instinto de sobrevivência, sua sagacidade fora do comum e suas habilidades de improvisação superadas somente pelo apetite insaciável dos dois.',
    genre: 'Animação, Comédia',
    director: 'Zac Moncrief',
    casting: ''
  }
};
