export const cartoonsDetails = {
  regularShow: {
    cartoonId: 'regularShow',
    titlePt: 'Apenas Um Show',
    titleEn: 'Regular Show',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  jorelsBrother: {
    cartoonId: 'jorelsBrother',
    titlePt: 'Irmão do Jorel',
    titleEn: 'Jorel\'s Brother',
    duration: 10,
    year: 2014,
    origin: 'Brasil',
    contentClassification: 'Obra não publicitária brasileira, constituinte de espaço qualificado e independente',
    indicativeClassification: '10',
    synopsis: 'Irmão do Jorel é o filho caçula de uma excêntrica família de acumuladores presa nos anos 80 e com a ajuda de sua melhor amiga, ele enfrenta os primeiros obstáculos da vida num ritmo alucinante. Sem diferenciar fantasia e realidade, ele sempre descobre uma maneira absurda de sair da sombra de seu irmão celebridade, mas seu verdadeiro nome é sempre um mistério para todos.',
    genre: 'Animação, Comédia',
    director: 'Juliano Enrico',
    casting: ''
  },
  thePowerpuffGirls: {
    cartoonId: 'thePowerpuffGirls',
    titlePt: 'As Meninas Superpoderosas',
    titleEn: 'The Powerpuff Girls',
    duration: 60,
    year: 2016,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 'Livre',
    synopsis: 'A cidade de Townsville pode ser uma metrópole bela e agitada, mas não se deixe enganar! O mal está à espreita e somente três menininhas superpoderosas são capazes de manter os vilões bem longe: Florzinha, Lindinha e Docinho! Conciliar a escola, a hora de dormir e derrotar monstros gigantes é mesmo complicado, mas, juntas, As Meninas Superpoderosas dão conta do recado! Enfrentando um bando de vilões, elas mostram o verdadeiro significado da frase "brigar como uma menininha". Novos inimigos e novas aventuras aguardam você na estreia da nova série de As Meninas Superpoderosas!',
    genre: 'Animação, Aventura, Comédia',
    director: 'Craig Mccraken',
    casting: ''
  },
  tomAndJerry: {
    cartoonId: 'tomAndJerry',
    titlePt: 'O Show de Tom e Jerry',
    titleEn: 'The Tom & Jerry Show',
    duration: 15,
    year: 2013,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 'Livre',
    synopsis: 'Junte-se a Tom e Jerry enquanto os dois disputam território. Eles vão aprontar novas e hilárias travessuras, torcendo para não ser pegos!',
    genre: 'Animação',
    director: '',
    casting: ''
  },
  dragonBall: {
    cartoonId: 'dragonBall',
    titlePt: 'Dragon Ball Super',
    titleEn: 'Dragon Ball Super',
    duration: 30,
    year: 2015,
    origin: 'Japão',
    contentClassification: '04',
    indicativeClassification: '10',
    synopsis: 'Após a derrota de Majin Buu, Goku assumiu o novo papel de... produtor de rabanetes?! A Terra está em paz e nossos heróis agora levam vidas normais. Mas eles não podem se acomodar. Num lugar distante, o poderoso Deus da Destruição, Beerus, desperta para uma profecia que revela seu fim pelas mãos de um ser ainda mais formidável. Quando a busca pelo Deus Saiyan os traz à Terra, poderão Goku e seus amigos enfrentar seu inimigo mais forte até hoje?',
    genre: 'Anime',
    director: '',
    casting: ''
  },
  scoobyDoo: {
    cartoonId: 'scoobyDoo',
    titlePt: 'Que Legal, Scooby-Doo!',
    titleEn: 'Be Cool Scooby Doo',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 'Livre',
    synopsis: 'A gangue põe o pé na estrada mais uma vez, a bordo da Máquina de Mistério, em busca de diversão e aventura. O problema é que os monstros e a confusão continuam no caminho! Desta vez, a galera vai tentar solucionar os novos e infindáveis enigmas que a espera. Por sorte, Salsicha e Scooby estão mais "corajosos e heroicos" do que nunca... à sua própria moda, é claro: com seu famoso instinto de sobrevivência, sua sagacidade fora do comum e suas habilidades de improvisação superadas somente pelo apetite insaciável dos dois.',
    genre: 'Animação, Comédia',
    director: 'Zac Moncrief',
    casting: ''
  },
  stevenUniverse: {
    cartoonId: 'stevenUniverse',
    titlePt: 'Steven Universe',
    titleEn: 'Steven Universe',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  adventureTime: {
    cartoonId: 'adventureTime',
    titlePt: 'Hora da Aventure',
    titleEn: 'Adventure Time',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  gumball: {
    cartoonId: 'gumball',
    titlePt: 'O Incrivel Mundo de Gumball',
    titleEn: 'The Amazing World of Gumball',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  johnnyBravo: {
    cartoonId: 'johnnyBravo',
    titlePt: 'Johnny Bravo',
    titleEn: 'Johnny Bravo',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  courage: {
    cartoonId: 'courage',
    titlePt: 'Coragem, o Cão Covarde',
    titleEn: 'Courage, the Coward Dog',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  campLazlo: {
    cartoonId: 'campLazlo',
    titlePt: 'O Acampamento de Lazlo',
    titleEn: 'Camp Lazlo',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  dexter: {
    cartoonId: 'dexter',
    titlePt: 'O Laboratório de Dexter',
    titleEn: 'Dexter\'s Laboratory',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  mrBean: {
    cartoonId: 'mrBean',
    titlePt: 'Mr. Bean',
    titleEn: 'Mr. Bean',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  pinkPanther: {
    cartoonId: 'pinkPanther',
    titlePt: 'A Turma da Pantera Cor de Rosa',
    titleEn: 'Pink Panther & Pals',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  clarence: {
    cartoonId: 'clarence',
    titlePt: 'Clarêncio, o Otimista',
    titleEn: 'Clarence',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  monica: {
    cartoonId: 'monica',
    titlePt: 'Turma da Mônica',
    titleEn: 'Monica and Friends',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  lego: {
    cartoonId: 'lego',
    titlePt: 'Lego: Nexo Knights',
    titleEn: 'Lego: Nexo Knights',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  teenTitans: {
    cartoonId: 'teenTitans',
    titlePt: 'Os Jovens Titãs em Ação',
    titleEn: 'Teen Titans Go!',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  ben10: {
    cartoonId: 'ben10',
    titlePt: 'Ben 10',
    titleEn: 'Ben 10',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  picapauAmarelo: {
    cartoonId: 'picapauAmarelo',
    titlePt: 'Sitio do Picapau Amarelo',
    titleEn: 'Sitio do Picapau Amarelo',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  trunkTrain: {
    cartoonId: 'trunkTrain',
    titlePt: 'Tromba Trem',
    titleEn: 'Trunk Train',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  surfsUp: {
    cartoonId: 'surfsUp',
    titlePt: 'Tá Dando Onda',
    titleEn: 'Surf\'s Up',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  weBareBears: {
    cartoonId: 'weBareBears',
    titlePt: 'Ursos Sem Curso',
    titleEn: 'We Bare Bears',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  magisWords: {
    cartoonId: 'magisWords',
    titlePt: 'Poderosas Magiespadas',
    titleEn: 'Mighty Magiswords',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  transformers: {
    cartoonId: 'transformers',
    titlePt: 'Transformers Robots in Disguise',
    titleEn: 'Transformers Robots in Disguise',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  powerRangers: {
    cartoonId: 'powerRangers',
    titlePt: 'Power Rangers Ninja Steel',
    titleEn: 'Power Rangers Ninja Steel',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  uncleGrandpa: {
    cartoonId: 'uncleGrandpa',
    titlePt: 'Titio Avô',
    titleEn: 'Uncle Grandpa',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  billyAndMandy: {
    cartoonId: 'billyAndMandy',
    titlePt: 'As Terríveis Aventuras de Billy e Mandy',
    titleEn: 'The Grim Adventures of Billy & Mandy',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  weasel: {
    cartoonId: 'weasel',
    titlePt: 'Eu sou o máximo',
    titleEn: 'I am Weasel',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  scoobyDooAndVampire: {
    cartoonId: 'scoobyDooAndVampire',
    titlePt: 'Scooby-Doo e a Lenda do Vampiro',
    titleEn: 'Scooby-Doo and the Legend of the Vampire',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  bunnicula: {
    cartoonId: 'bunnicula',
    titlePt: 'Bunnicula, o Vampiro Coelho',
    titleEn: 'Bunnicula',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  barbie: {
    cartoonId: 'barbie',
    titlePt: 'Barbie',
    titleEn: 'Barbie',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  monsterHigh: {
    cartoonId: 'monsterHigh',
    titlePt: 'Monster High',
    titleEn: 'Monster High',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  drSeuss: {
    cartoonId: 'drSeuss',
    titlePt: 'Dr. Seuss',
    titleEn: 'Dr. Seuss',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  barbieVideoGame: {
    cartoonId: 'barbieVideoGame',
    titlePt: 'Barbie em um Mundo de Video Game',
    titleEn: 'Barbie Video Game Hero',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  dragonBallZ: {
    cartoonId: 'dragonBallZ',
    titlePt: 'Dragon Ball Z',
    titleEn: 'Dragon Ball Z',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  mashaAndTheBear: {
    cartoonId: 'mashaAndTheBear',
    titlePt: 'Masha e o Urso',
    titleEn: 'Masha and the Bear',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  theHapposFamily: {
    cartoonId: 'theHapposFamily',
    titlePt: 'The Happos Family',
    titleEn: 'The Happos Family',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  oddbods: {
    cartoonId: 'oddbods',
    titlePt: 'Oddbods',
    titleEn: 'Oddbods',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  pokemon: {
    cartoonId: 'pokemon',
    titlePt: 'Pokemon',
    titleEn: 'Pokemon',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  },
  oswaldo: {
    cartoonId: 'oswaldo',
    titlePt: 'Oswaldo',
    titleEn: 'Oswaldo',
    duration: 30,
    year: 2015,
    origin: 'Estados Unidos',
    contentClassification: '04',
    indicativeClassification: 10,
    synopsis: 'O programa tem como protagonistas dois zeladores de um parque: um gaio-azul de mais de 1,80 m de altura chamado Mordecai, e um guaxinim chamado Rigby. Mordecai e Rigby são melhores amigos que passam seus dias tentando se divertir, de todas as maneiras possíveis',
    genre: 'Animação, Comédia',
    director: 'Jhon Iinfantino',
    casting: 'J.G. Quintel'
  }
};
